//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionApp.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS
    {
        public int id { get; set; }
        public string tipo_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public int id_estado { get; set; }
        public int id_viajero { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual PASAJEROS PASAJEROS { get; set; }
    }
}
