//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionApp.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJEROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PASAJEROS()
        {
            this.DOCUMENTOS = new HashSet<DOCUMENTOS>();
            this.VIAJES_TRANSITO_MIGRACION = new HashSet<VIAJES_TRANSITO_MIGRACION>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string correo_electronico { get; set; }
        public int genero_fk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual GENEROS GENEROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES_TRANSITO_MIGRACION> VIAJES_TRANSITO_MIGRACION { get; set; }
    }
}
