//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionApp.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES_TRANSITO_MIGRACION
    {
        public int id { get; set; }
        public int id_viajero { get; set; }
        public System.DateTime fecha { get; set; }
        public string destino { get; set; }
        public string origen { get; set; }
        public string tipo_solicitud { get; set; }
        public string motivo_viaje { get; set; }
        public int id_usuario { get; set; }
    
        public virtual PASAJEROS PASAJEROS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
